//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDT_23TH0014.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSanPham
    {
        public string MaSP { get; set; }
        public string MaMau { get; set; }
        public string AnhBia { get; set; }
    
        public virtual MauSac MauSac { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
